### ISSUE TITLE
Research Schema Migration solutions

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/sqlq#21]

**Comment by amenowanna** [comment]
@riyaz-ali As you are moving forward with the first use of SQLQ in MergeStat I want us to document your experience and thoughts on using the migrations that you have in the tool. If you feel this is the correct path forward for migrations then let's move forward with that for now and update the documentation for this. One main thing I think a tradeoff we have to accept there is that the migration will depend on the library. If this path is not the one we choose to use then @ramiroJCB and I have discussed and agree that sicking with go-migrate with the enhancements we have made of adding a history table and not letting migrations stay marked as dirty addresses the main issues we have with that tool. The benefit we also get with that tool is that since it has a CLI it could be used separately from the library for anyone just wanting a path for the schema without the library. Please document what you think here. @patrickdevivo for visibility.

**Comment by amenowanna** [comment]
@patrickdevivo @ramiroJCB @riyaz-ali I have been really happy with the migration solution that @riyaz-ali has created. I propose that we look at publishing this as its own tool so we can then also leverage it for any schema we may be running as it is possible we may even want our sync to manage their own schema. I have yet to find another tool that more closely meets the criteria I had define in my original research [ticket](https://github.com/mergestat/mergestat/issues/331).

**Comment by riyaz-ali** [comment]
I'll spend some time on this after I'm done with my current work and refine the scope of having such a project and try to come up with a more formal proposal 👍
